Remove unecessary Ownable, and create a compile script for yarn
flavor-finance/flavor-prize-strategy pull request #1
Opened 2020-10-06 07:42 UTC by mikeki

Still doesn't compile but now you can run
`yarn compile` to compile the contracts and see where's the error at.

2020-10-06 15:18 UTC, jamslevy requested changes

2020-10-06 15:18 UTC, jamslevy commented on contracts/FlavorStrategy.sol
> -import "./Ownable.sol";
@mikeki The contract still inherits from Ownable and uses the `onlyOwner` modifier for the `addPodAddress` function.

2020-10-06 17:11 UTC, mikeki commented on contracts/FlavorStrategy.sol
> -import "./Ownable.sol";
Ownable is already in scope, it's added with the @pooltogether contracts

2020-10-07 04:53 UTC, mikeki commented
merging to keep improving on it

2020-10-07 04:53 UTC, merged